In [2]:
import numpy as np
import pandas as pd

## Load individual CSVs from corsica

In [31]:
df_2018 = pd.read_csv('D:/Python/Insight/csv_data/corsica/raw/2018.txt')
df_2017 = pd.read_csv('D:/Python/Insight/csv_data/corsica/raw/2017.txt')
df_2016 = pd.read_csv('D:/Python/Insight/csv_data/corsica/raw/2016.txt')
df_2015 = pd.read_csv('D:/Python/Insight/csv_data/corsica/raw/2015.txt')
df_2014 = pd.read_csv('D:/Python/Insight/csv_data/corsica/raw/2014.txt')
df_2013 = pd.read_csv('D:/Python/Insight/csv_data/corsica/raw/2013.txt')
df_2012 = pd.read_csv('D:/Python/Insight/csv_data/corsica/raw/2012.txt')
df_2011 = pd.read_csv('D:/Python/Insight/csv_data/corsica/raw/2011.txt')
df_2010 = pd.read_csv('D:/Python/Insight/csv_data/corsica/raw/2010.txt')
df_2009 = pd.read_csv('D:/Python/Insight/csv_data/corsica/raw/2009.txt')
df_2008 = pd.read_csv('D:/Python/Insight/csv_data/corsica/raw/2008.txt')

df = pd.concat([df_2018,df_2017,df_2016,df_2015,df_2014,df_2013,df_2012,df_2011,df_2010,df_2009,df_2008])

df = df.reset_index(drop=True)

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:13: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  del sys.path[0]

## Match name tag/keys

In [32]:
firstname= []
lastname = []

for i in range(0,len(df)):
    
    name = df['Player'][i]
    
    if '.' in name:
        if '..' in name:
            idi= [pos for pos, char in enumerate(name) if char == '.']
            firstname.append(name[:idi[0]][0] + '.' + name[:idi[0]][2] + '.')
            lastname.append(name[idi[1]+1:])
        elif '.' in name:
            idi= [pos for pos, char in enumerate(name) if char == '.']
            idi2= [pos for pos, char in enumerate(name) if char == ' ']
            firstname.append(name[:idi2[0]])
            lastname.append(name[idi2[0]+1:])
    elif '-' in name:
        idi= [pos for pos, char in enumerate(name) if char == '-']
        idi2= [pos for pos, char in enumerate(name) if char == ' ']
        if int(idi[0]) > int(idi2[0]): # Surname
            firstname.append(name[:idi2[0]])
            lastname.append(name[idi2[0]+1:])
        else:
            firstname.append(name[:idi2[0]])
            lastname.append(name[idi2[0]+1:])
    elif '(' in name:
        idi= [pos for pos, char in enumerate(name) if char == '(']
        idi2= [pos for pos, char in enumerate(name) if char == ')']
        idi3=  [pos for pos, char in enumerate(name) if char == ' ']

        name = name[:idi[0]-1] + name[idi2[0]+1:]
        firstname.append(name[:idi3[0]])
        lastname.append(name[idi3[0]+1:])

    elif ' ' in name:
        idi=  [pos for pos, char in enumerate(name) if char == ' ']
        firstname.append(name[:idi[0]])
        lastname.append(name[idi[0]+1:])
 

df['Firstname'] = firstname
df['Lastname']  = lastname
df['Lastname'] = df.Lastname.str.capitalize()
df['Firstname'] = df.Firstname.str.capitalize()

In [33]:
df1=df.reset_index(drop=True)

In [34]:
df1['Lastname_1'] = df1.Lastname.str.replace('-' , '')
df1['Lastname_1'] = df1.Lastname_1.str.replace('.' , '')
df1['Lastname_1'] = df1.Lastname_1.str.replace('(' , '')
df1['Lastname_1'] = df1.Lastname_1.str.replace(')' , '')
df1['Lastname_1'] = df1.Lastname_1.str.replace(' ' , '')
df1['Lastname_1'] = df1.Lastname_1.str.replace(r"[']" , '')

df1['Firstname_1'] = df1.Firstname.str.replace('-' , '')
df1['Firstname_1'] = df1.Firstname_1.str.replace('.' , '')
df1['Firstname_1'] = df1.Firstname_1.str.replace(')' , '')
df1['Firstname_1'] = df1.Firstname_1.str.replace('(' , '')
df1['Firstname_1'] = df1.Firstname_1.str.replace(' ' , '')
df1['Firstname_1'] = df1.Firstname_1.str.replace(r"['']", '')

In [35]:
codes=[]
years=[]


for i in range(0,len(df1)):
    
   
    codes.append((df1['Lastname_1'][i][0:5] + df1['Firstname_1'][i][0:2]).lower())
    idi= [pos for pos, char in enumerate(df['Season'][i]) if char == '-']
    years.append(2000 + int(df['Season'][i][idi[0]+1:]))
df1['Code'] = codes
df1['Years'] = years

df1 = df1.reset_index(drop=True)

In [36]:
df1 = df1.sort_values(['Lastname','Years']).reset_index(drop=True)
df1.head(50)

,A,C+/-,CA,CF,CF%,CF% QoC,CF% QoT,G,G+/-,GA,...,xG+/-,xGA,xGF,xGF%,Firstname,Lastname,Lastname_1,Firstname_1,Code,Years
0,--,-7,12,5,29.41,51.99,44.38,--,-2,2,...,-0.27,0.59,0.32,35.16,Spencer,Abbott,Abbott,Spencer,abbotsp,2014
1,--,5,7,12,63.16,46.95,50.34,--,--,--,...,-0.1,0.27,0.17,38.64,Spencer,Abbott,Abbott,Spencer,abbotsp,2017
2,--,1,18,19,51.35,50.52,57.53,--,--,1,...,0.49,0.49,0.98,66.67,Justin,Abdelkader,Abdelkader,Justin,abdelju,2008
3,--,13,9,22,70.97,52.09,57.49,--,--,--,...,0.62,0.24,0.86,78.18,Justin,Abdelkader,Abdelkader,Justin,abdelju,2009
4,3,29,376,405,51.86,49.37,51.18,3,-12,21,...,1.85,14.54,16.39,52.99,Justin,Abdelkader,Abdelkader,Justin,abdelju,2010
5,11,132,623,755,54.79,49.69,53.65,7,13,20,...,8.17,23.08,31.25,57.52,Justin,Abdelkader,Abdelkader,Justin,abdelju,2011
6,14,102,695,797,53.42,49.41,54.46,8,5,27,...,2.34,31.81,34.15,51.77,Justin,Abdelkader,Abdelkader,Justin,abdelju,2012
7,3,120,472,592,55.64,49.76,52.31,8,6,14,...,2.63,19.87,22.5,53.1,Justin,Abdelkader,Abdelkader,Justin,abdelju,2013
8,15,24,804,828,50.74,50.11,51.62,9,5,33,...,1.31,32.23,33.54,51,Justin,Abdelkader,Abdelkader,Justin,abdelju,2014
9,12,183,673,856,55.98,49.58,52.17,14,9,31,...,7.39,27.93,35.32,55.84,Justin,Abdelkader,Abdelkader,Justin,abdelju,2015
10,13,-5,938,933,49.87,49.82,52.6,11,-10,45,...,-5.47,46.3,40.83,46.86,Justin,Abdelkader,Abdelkader,Justin,abdelju,2016
11,8,-119,762,643,45.77,50.40,48.9,2,-19,36,...,-7.67,34.88,27.21,43.82,Justin,Abdelkader,Abdelkader,Justin,abdelju,2017
12,13,-33,867,834,49.03,49.91,48.47,9,-9,42,...,-3.45,38.46,35.01,47.65,Justin,Abdelkader,Abdelkader,Justin,abdelju,2018
13,1,-21,156,135,46.39,49.42,51.44,1,-2,7,...,-0.43,5.57,5.14,47.99,Pontus,Aberg,Aberg,Pontus,abergpo,2017
14,11,-83,604,521,46.31,50.26,50.85,4,10,17,...,-1.2,24.2,23,48.73,Pontus,Aberg,Aberg,Pontus,abergpo,2018
15,1,1,136,137,50.18,50.02,47.56,--,-4,8,...,1.24,4.51,5.75,56.04,Noel,Acciari,Acciari,Noel,acciano,2016
16,3,-8,239,231,49.15,49.85,52.66,2,3,6,...,2.4,7.87,10.27,56.62,Noel,Acciari,Acciari,Noel,acciano,2017
17,1,-32,603,571,48.64,49.99,53.33,8,-10,25,...,1.7,22.32,24.02,51.83,Noel,Acciari,Acciari,Noel,acciano,2018
18,2,-65,178,113,38.83,49.36,43.21,3,-2,7,...,-3.18,6.93,3.75,35.11,Will,Acton,Acton,Will,actonwi,2014
19,--,-5,26,21,44.68,50.89,47.26,--,-2,3,...,-0.44,0.85,0.41,32.54,Will,Acton,Acton,Will,actonwi,2015
20,--,-44,196,152,43.68,49.93,49.74,3,-4,8,...,-1.02,7.99,6.97,46.59,Luke,Adam,Adam,Luke,adamlu,2011
21,7,-11,487,476,49.43,49.84,48.93,10,-3,23,...,-3.23,21.65,18.42,45.97,Luke,Adam,Adam,Luke,adamlu,2012
22,--,-24,46,22,32.35,52.08,45.98,1,1,1,...,-0.75,1.5,0.75,33.33,Luke,Adam,Adam,Luke,adamlu,2013
23,--,-1,117,116,49.79,50.11,43.27,1,--,3,...,-1.13,4.38,3.25,42.6,Luke,Adam,Adam,Luke,adamlu,2014
24,--,--,9,9,50,49.21,44.25,--,--,--,...,-0.55,0.63,0.08,11.27,Luke,Adam,Adam,Luke,adamlu,2015
25,5,-99,513,414,44.66,49.98,49.89,2,-20,30,...,-8.2,23.03,14.83,39.17,Craig,Adams,Adams,Craig,adamscr,2008
26,--,-15,142,127,47.21,51.78,49.5,--,-9,11,...,-2.58,7.2,4.62,39.09,Kevyn,Adams,Adams,Kevyn,adamske,2008
27,3,33,269,302,52.89,49.53,52.56,1,-4,9,...,-0.03,11.14,11.11,49.93,Craig,Adams,Adams,Craig,adamscr,2009
28,9,-92,595,503,45.81,49.33,52.27,--,-6,23,...,-3.33,21.22,17.89,45.74,Craig,Adams,Adams,Craig,adamscr,2010
29,7,-72,630,558,46.97,49.65,53.12,1,-12,27,...,-3.77,22.79,19.02,45.49,Craig,Adams,Adams,Craig,adamscr,2011
30,10,-13,534,521,49.38,49.36,53.71,5,-9,30,...,0.68,20.39,21.07,50.82,Craig,Adams,Adams,Craig,adamscr,2012
31,6,-90,365,275,42.97,49.78,47.06,1,-4,13,...,-0.52,11.22,10.7,48.81,Craig,Adams,Adams,Craig,adamscr,2013
32,4,-210,695,485,41.1,49.61,47.51,4,-19,32,...,-5.84,23.73,17.89,42.98,Craig,Adams,Adams,Craig,adamscr,2014
33,5,-33,387,354,47.77,49.83,50.43,1,-4,14,...,-2.55,15.21,12.66,45.43,Craig,Adams,Adams,Craig,adamscr,2015
34,11,106,516,622,54.66,49.92,48.93,8,-10,35,...,3.6,22.3,25.9,53.73,Maxim,Afinogenov,Afinogenov,Maxim,afinoma,2008
35,7,38,441,479,52.07,48.82,48.76,5,-7,25,...,-2.14,18.83,16.69,46.99,Maxim,Afinogenov,Afinogenov,Maxim,afinoma,2009
36,25,-68,1081,1013,48.38,49.84,49.53,15,-12,65,...,-10.5,49.77,39.27,44.1,Maxim,Afinogenov,Afinogenov,Maxim,afinoma,2010
37,1,-24,95,71,42.77,50.75,44.43,1,-2,4,...,-0.9,4.45,3.55,44.38,Kenny,Agostino,Agostino,Kenny,agostke,2014
38,--,4,18,22,55,48.80,49.89,--,-1,1,...,0.11,0.9,1.01,52.88,Kenny,Agostino,Agostino,Kenny,agostke,2016
39,1,21,65,86,56.95,49.34,49.19,1,--,3,...,1.6,3.13,4.73,60.18,Kenny,Agostino,Agostino,Kenny,agostke,2017
40,--,-15,49,34,40.96,48.88,52.62,--,-1,2,...,-0.49,2.23,1.74,43.83,Kenny,Agostino,Agostino,Kenny,agostke,2018
41,1,-6,14,8,36.36,53.03,44.05,--,1,--,...,-0.36,0.67,0.31,31.63,Andrew,Agozzino,Agozzino,Andrew,agozzan,2015
42,1,-14,73,59,44.7,51.07,43.91,--,-1,2,...,-0.25,2.47,2.22,47.33,Andrew,Agozzino,Agozzino,Andrew,agozzan,2016
43,12,127,952,1079,53.13,50.01,51.77,15,-1,44,...,5.17,45.05,50.22,52.71,Sebastian,Aho,Aho,Sebastian,ahose,2017
44,3,-36,328,292,47.1,50.09,47.38,--,-4,19,...,-4.88,15.89,11.01,40.93,Sebastian,Aho,Aho,Sebastian,ahose,2018
45,28,214,984,1198,54.9,49.64,54.35,18,6,51,...,8.27,44.89,53.16,54.22,Sebastian,Aho,Aho,Sebastian,ahose,2018
46,--,-1,14,13,48.15,53.38,48.39,1,2,--,...,0.21,0.71,0.92,56.44,Jason,Akeson,Akeson,Jason,akesoja,2013
47,1,6,11,17,60.71,51.42,49.26,--,1,1,...,0.76,0.22,0.98,81.67,Jason,Akeson,Akeson,Jason,akesoja,2014
48,--,-44,114,70,38.04,49.13,47.7,--,-1,2,...,-3.23,5.02,1.79,26.28,Jason,Akeson,Akeson,Jason,akesoja,2015
49,--,-8,45,37,45.12,48.72,49.33,1,-3,4,...,-0.4,1.76,1.36,43.59,John,Albert,Albert,John,alberjo,2014

## Load hockey-ref. and salary data

In [37]:
df2 = pd.read_csv('D:/Python/Insight/csv_data/all_data/All_data_HRef - data.csv') 
df2.head()

,Code,First_name,Last_name,Position,Shoots,Draft_year,Draft_round,Height,Weight,DOB,...,BLK,TKY,GWY,PDO,OZS,DZS,OPS,DPS,Salary,Cap_hit
0,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,0,1,0,98.6,60.0,40.0,-0.1,0.0,740000,740000
1,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,0,0,1,100.0,66.7,33.3,-0.1,0.0,740000,740000
2,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,20,7,7,94.3,66.3,33.7,-0.6,0.2,740000,740000
3,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,39,17,20,101.9,58.8,41.2,0.2,1.5,787500,787500
4,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,42,16,14,100.5,59.3,40.7,0.5,1.1,787500,787500

In [38]:
df2.Year

0        2008
1        2009
2        2010
3        2011
4        2012
5        2013
6        2014
7        2015
8        2016
9        2017
10       2018
11       2008
12       2008
13       2008
14       2009
15       2009
16       2009
17       2010
18       2011
19       2012
20       2013
21       2014
22       2015
23       2008
24       2008
25       2009
26       2010
27       2008
28       2009
29       2010
         ...
11178    2017
11179    2018
11180    2017
11181    2018
11182    2018
11183    2018
11184    2018
11185    2017
11186    2018
11187    2017
11188    2018
11189    2018
11190    2017
11191    2018
11192    2017
11193    2018
11194    2018
11195    2018
11196    2018
11197    2017
11198    2018
11199    2017
11200    2018
11201    2017
11202    2017
11203    2017
11204    2017
11205    2017
11206    2017
11207    2017
Name: Year, Length: 11208, dtype: int64

## Remove 'TOT' from data. This is data for years when a player played on more than one team

In [39]:
#df2_edit = df2[df2.Team != 'TOT'].reset_index(drop=True)
df2_edit=df2.copy()

## Plan to concat corsica to hockey-ref, hence adding required variables

In [40]:
df2_edit['P/60'] = [np.nan]*len(df2_edit)
df2_edit['P1/60'] = [np.nan]*len(df2_edit)
df2_edit['GS/60'] = [np.nan]*len(df2_edit)
df2_edit['CF'] = [np.nan]*len(df2_edit)
df2_edit['CA'] = [np.nan]*len(df2_edit)
df2_edit['CF%'] = [np.nan]*len(df2_edit)
df2_edit['Rel CF%'] = [np.nan]*len(df2_edit)
df2_edit['GF'] = [np.nan]*len(df2_edit)
df2_edit['GA'] = [np.nan]*len(df2_edit)
df2_edit['xGF'] = [np.nan]*len(df2_edit)
df2_edit['xGA'] = [np.nan]*len(df2_edit)
df2_edit['xGF%'] = [np.nan]*len(df2_edit)
df2_edit['Rel xGF%'] = [np.nan]*len(df2_edit)
df2_edit['Rel CF%'] = [np.nan]*len(df2_edit)
df2_edit['iPENT'] = [np.nan]*len(df2_edit)
df2_edit['iPEND'] = [np.nan]*len(df2_edit)
df2_edit['iSh%'] = [np.nan]*len(df2_edit)
df2_edit['ixGF'] = [np.nan]*len(df2_edit)
df2_edit['ixGF/60'] = [np.nan]*len(df2_edit)
df2_edit['ZSR'] = [np.nan]*len(df2_edit)
df2_edit['TOI%'] = [np.nan]*len(df2_edit)
df2_edit['TOI% QoT'] = [np.nan]*len(df2_edit)
df2_edit['CF% QoT'] = [np.nan]*len(df2_edit)
df2_edit['TOI% QoC'] = [np.nan]*len(df2_edit)
df2_edit['CF% QoC'] = [np.nan]*len(df2_edit)
df2_edit['GP'] = [np.nan]*len(df2_edit)
df2_edit['TOI'] = [np.nan]*len(df2_edit)
df2_edit['G'] = [np.nan]*len(df2_edit)
df2_edit['A'] = [np.nan]*len(df2_edit)
df2_edit['P'] = [np.nan]*len(df2_edit)
df2_edit['P1'] = [np.nan]*len(df2_edit)
df2_edit['GS'] = [np.nan]*len(df2_edit)
df2_edit['C+/-'] = [np.nan]*len(df2_edit)
df2_edit['G+/-'] = [np.nan]*len(df2_edit)
df2_edit['GF%'] = [np.nan]*len(df2_edit)
df2_edit['xGF%'] = [np.nan]*len(df2_edit)
df2_edit['xG+/-'] = [np.nan]*len(df2_edit)
df2_edit['iP+/-'] = [np.nan]*len(df2_edit)
df2_edit['iCF'] = [np.nan]*len(df2_edit)
df2_edit['iCF/60'] = [np.nan]*len(df2_edit)

df2_edit.index.name = 'Ind'
df2_edit.head(20)

,Code,First_name,Last_name,Position,Shoots,Draft_year,Draft_round,Height,Weight,DOB,...,P,P1,GS,C+/-,G+/-,GF%,xG+/-,iP+/-,iCF,iCF/60
Ind,,,,,,,,,,,,,,,,,,,,,
0,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,adamscr01,Craig,Adams,RW,R,1996,9.223,183,197,1977-04-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,adamscr01,Craig,Adams,RW,R,1996,9.223,183,197,1977-04-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,adamscr01,Craig,Adams,RW,R,1996,9.223,183,197,1977-04-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,adamscr01,Craig,Adams,RW,R,1996,9.223,183,197,1977-04-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,adamscr01,Craig,Adams,RW,R,1996,9.223,183,197,1977-04-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,adamscr01,Craig,Adams,RW,R,1996,9.223,183,197,1977-04-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,adamscr01,Craig,Adams,RW,R,1996,9.223,183,197,1977-04-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,adamscr01,Craig,Adams,RW,R,1996,9.223,183,197,1977-04-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,adamscr01,Craig,Adams,RW,R,1996,9.223,183,197,1977-04-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Add new variables

In [41]:
df1['Years']

0       2014
1       2017
2       2008
3       2009
4       2010
5       2011
6       2012
7       2013
8       2014
9       2015
10      2016
11      2017
12      2018
13      2017
14      2018
15      2016
16      2017
17      2018
18      2014
19      2015
20      2011
21      2012
22      2013
23      2014
24      2015
25      2008
26      2008
27      2009
28      2010
29      2011
        ...
9693    2008
9694    2009
9695    2009
9696    2008
9697    2009
9698    2010
9699    2011
9700    2012
9701    2013
9702    2014
9703    2015
9704    2016
9705    2011
9706    2012
9707    2013
9708    2014
9709    2015
9710    2016
9711    2017
9712    2018
9713    2012
9714    2013
9715    2014
9716    2015
9717    2016
9718    2017
9719    2018
9720    2017
9721    2018
9722    2008
Name: Years, Length: 9723, dtype: int64

In [42]:
for i in range(0,len(df1)):

    year = df1['Years'][i]
    team = df1['Team'][i]

    potentials = df2_edit[df2_edit.Code.str.contains(df1['Code'][i], regex='True')]
    uniques = potentials['Code'].unique()

    if len(uniques) < 2:
        
        info= potentials[potentials['Year'] == year]
        idi = info.index.values.tolist()
        #df2_edit['CF% QOC'][idi] = df1['CF% QoC'][i]
        
        df2_edit['P/60'][idi]     = df1['P/60'][i]    
        df2_edit['P1/60'][idi]    = df1['P1/60'][i]   
        df2_edit['GS/60'][idi]    = df1['GS/60'][i]   
        df2_edit['CF'][idi]       = df1['CF'][i]      
        df2_edit['CA'][idi]       = df1['CA'][i]      
        df2_edit['CF%'][idi]      = df1['CF%'][i]     
        df2_edit['Rel CF%'][idi]  = df1['Rel CF%'][i] 
        df2_edit['GF'][idi]       = df1['GF'][i]      
        df2_edit['GA'][idi]       = df1['GA'][i]      
        df2_edit['xGF'][idi]      = df1['xGF'][i]     
        df2_edit['xGA'][idi]      = df1['xGA'][i]     
        df2_edit['xGF%'][idi]     = df1['xGF%'][i]    
        df2_edit['Rel xGF%'][idi] = df1['Rel xGF%'][i]
        df2_edit['Rel CF%'][idi]  = df1['Rel CF%'][i] 
        df2_edit['iPENT'][idi]    = df1['iPENT'][i]   
        df2_edit['iPEND'][idi]    = df1['iPEND'][i]
        df2_edit['iSh%'][idi]     = df1['iSh%'][i]
        df2_edit['ixGF'][idi]     = df1['ixGF'][i]
        df2_edit['ixGF/60'][idi]  = df1['ixGF/60'][i] 
        df2_edit['ZSR'][idi]      = df1['ZSR'][i]     
        df2_edit['TOI%'][idi]     = df1['TOI%'][i]    
        df2_edit['TOI% QoT'][idi] = df1['TOI% QoT'][i]
        df2_edit['CF% QoT'][idi]  = df1['CF% QoT'][i] 
        df2_edit['TOI% QoC'][idi] = df1['TOI% QoC'][i]
        df2_edit['CF% QoC'][idi]  = df1['CF% QoC'][i] 
        df2_edit['GP'][idi]       = df1['GP'][i]
        df2_edit['TOI'][idi]      = df1['TOI'][i]
        df2_edit['G'][idi]        = df1['G'][i]
        df2_edit['A'][idi]        = df1['A'][i]
        df2_edit['P'][idi]        = df1['P'][i]
        df2_edit['P1'][idi]       = df1['P1'][i]
        df2_edit['GS'][idi]       = df1['GS'][i]
        df2_edit['C+/-'][idi]     = df1['C+/-'][i]
        df2_edit['G+/-'][idi]     = df1['G+/-'][i]
        df2_edit['GF%'][idi]      = df1['GF%'][i]
        df2_edit['xGF%'][idi]     = df1['xGF%'][i]
        df2_edit['xG+/-'][idi]   = df1['xG+/-'][i]
        df2_edit['iP+/-'][idi]    = df1['iP+/-'][i]
        df2_edit['iCF'][idi]     = df1['iCF'][i]
        df2_edit['iCF/60'][idi]   = df1['iCF/60'][i]

    else:
        
        for j in range(0,len(uniques)):
            
            player = df2_edit[df2_edit['Code'] == uniques[j]]
            
            info = player[(player['Team'] == team) & (player['Year'] == year)] 
            
            if not info.empty:
                
                idi = info.index.values.tolist()
                
                df2_edit['P/60'][idi]     = df1['P/60'][i]    
                df2_edit['P1/60'][idi]    = df1['P1/60'][i]   
                df2_edit['GS/60'][idi]    = df1['GS/60'][i]   
                df2_edit['CF'][idi]       = df1['CF'][i]      
                df2_edit['CA'][idi]       = df1['CA'][i]      
                df2_edit['CF%'][idi]      = df1['CF%'][i]     
                df2_edit['Rel CF%'][idi]  = df1['Rel CF%'][i] 
                df2_edit['GF'][idi]       = df1['GF'][i]      
                df2_edit['GA'][idi]       = df1['GA'][i]      
                df2_edit['xGF'][idi]      = df1['xGF'][i]     
                df2_edit['xGA'][idi]      = df1['xGA'][i]     
                df2_edit['xGF%'][idi]     = df1['xGF%'][i]    
                df2_edit['Rel xGF%'][idi] = df1['Rel xGF%'][i]
                df2_edit['Rel CF%'][idi]  = df1['Rel CF%'][i] 
                df2_edit['iPENT'][idi]    = df1['iPENT'][i]   
                df2_edit['iPEND'][idi]    = df1['iPEND'][i]
                df2_edit['iSh%'][idi]     = df1['iSh%'][i]
                df2_edit['ixGF'][idi]     = df1['ixGF'][i]
                df2_edit['ixGF/60'][idi]  = df1['ixGF/60'][i] 
                df2_edit['ZSR'][idi]      = df1['ZSR'][i]     
                df2_edit['TOI%'][idi]     = df1['TOI%'][i]    
                df2_edit['TOI% QoT'][idi] = df1['TOI% QoT'][i]
                df2_edit['CF% QoT'][idi]  = df1['CF% QoT'][i] 
                df2_edit['TOI% QoC'][idi] = df1['TOI% QoC'][i]
                df2_edit['CF% QoC'][idi]  = df1['CF% QoC'][i]
                df2_edit['GP'][idi]       = df1['GP'][i]
                df2_edit['TOI'][idi]      = df1['TOI'][i]
                df2_edit['G'][idi]        = df1['G'][i]
                df2_edit['A'][idi]        = df1['A'][i]
                df2_edit['P'][idi]        = df1['P'][i]
                df2_edit['P1'][idi]       = df1['P1'][i]
                df2_edit['GS'][idi]       = df1['GS'][i]
                df2_edit['C+/-'][idi]     = df1['C+/-'][i]
                df2_edit['G+/-'][idi]     = df1['G+/-'][i]
                df2_edit['GF%'][idi]      = df1['GF%'][i]
                df2_edit['xGF%'][idi]     = df1['xGF%'][i]
                df2_edit['xG+/-'][idi]   = df1['xG+/-'][i]
                df2_edit['iP+/-'][idi]    = df1['iP+/-'][i]
                df2_edit['iCF'][idi]     = df1['iCF'][i]
                df2_edit['iCF/60'][idi]   = df1['iCF/60'][i]

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:81: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:82: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:86: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:87: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:89: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:92: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:93: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:94: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:95: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:96: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:97: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:98: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:100: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:101: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:104: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:107: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
df1.keys()

Index(['Player', 'Season', 'Team', 'Position', 'GP', 'TOI', 'G', 'A', 'P',
       'P1', 'P/60', 'P1/60', 'GS', 'GS/60', 'CF', 'CA', 'C+/-', 'CF%',
       'Rel CF%', 'GF', 'GA', 'G+/-', 'GF%', 'Rel GF%', 'xGF', 'xGA', 'xG+/-',
       'xGF%', 'Rel xGF%', 'iPENT', 'iPEND', 'iP+/-', 'iCF', 'iCF/60', 'ixGF',
       'ixGF/60', 'iSh%', 'PDO', 'ZSR', 'TOI%', 'TOI% QoT', 'CF% QoT',
       'TOI% QoC', 'CF% QoC', 'Firstname', 'Lastname', 'Lastname_1',
       'Firstname_1', 'Code', 'Years'],
      dtype='object')

In [43]:
#potentials = df2_edit[df2_edit.Code.str.contains('adamscr', regex='True')]
#ids = potentials.index.values.tolist()
#uniques = potentials['Code'].unique()

In [44]:
#df2_edit[(df2_edit['First_name'] == 'Marcel') & (df2_edit['Team'] == 'NYR') ]

## Replace empty data with nans

In [45]:
df2_edit[df2_edit==-999]=np.nan
#df2_edit[df2_edit==-'999']=np.nan
df2_edit[df2_edit=='--']=np.nan

In [46]:
df2_edit.head()

,Code,First_name,Last_name,Position,Shoots,Draft_year,Draft_round,Height,Weight,DOB,...,P,P1,GS,C+/-,G+/-,GF%,xG+/-,iP+/-,iCF,iCF/60
Ind,,,,,,,,,,,,,,,,,,,,,
0,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,NaN,NaN,0.38,1,NaN,50,0.49,-1,8,20.85
1,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,NaN,NaN,0.81,13,NaN,NaN,0.62,NaN,7,22.6
2,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,6,6,11,29,-12,NaN,1.85,3,132,16.55
3,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,18,14,31.52,132,13,62.26,8.17,NaN,212,16.57
4,abdelju01,Justin,Abdelkader,LW,L,2005,2.042,188,214,1987-02-25,...,22,20,33.72,102,5,54.24,2.34,11,189,13.04

## Save to file

In [47]:
df2_edit.to_csv('out_with_TOT.csv', sep=',')